#!/usr/bin/env node
/**
 * Generates React components and brand tokens from the vector masters.
 *
 *   logos/svg/*.svg        -> src/generated/logos.tsx
 *   colors/palette.json    -> src/generated/tokens.ts
 *
 * The SVG and palette files stay the single source of truth: edit those, then run
 * `npm run generate` (it also runs automatically before `npm run build`).
 */
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const svgDir = join(root, 'logos', 'svg');
const outDir = join(root, 'src', 'generated');
mkdirSync(outDir, { recursive: true });

const HEADER = '// AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.\n';

// ---------------------------------------------------------------- logos
const ATTRS = {
  'stroke-width': 'strokeWidth',
  'stroke-linejoin': 'strokeLinejoin',
  'stroke-opacity': 'strokeOpacity',
  'paint-order': 'paintOrder',
};

const pascal = (s) => s.split('-').map((w) => w[0].toUpperCase() + w.slice(1)).join('');

function componentName(file) {
  const base = file.replace(/\.svg$/, '');
  let m = base.match(/^gfi-(horizontal|stacked|icon-simple|icon)-for-(light|dark)-bg$/);
  if (m) return `Logo${pascal(m[1])}On${pascal(m[2])}`;
  m = base.match(/^gfi-(horizontal|stacked)-(light|dark)-with-background$/);
  if (m) return `Logo${pascal(m[1])}${pascal(m[2])}WithBackground`;
  throw new Error(`Unrecognised logo file name: ${file}`);
}

function toJsx(markup) {
  let out = markup.replace(/<title>[\s\S]*?<\/title>\s*/g, '');
  for (const [from, to] of Object.entries(ATTRS)) out = out.replaceAll(` ${from}=`, ` ${to}=`);
  return out.trim();
}

const files = readdirSync(svgDir).filter((f) => f.endsWith('.svg')).sort();
const entries = [];
let body = '';
for (const file of files) {
  const svg = readFileSync(join(svgDir, file), 'utf8');
  const [, vw, vh] = svg.match(/viewBox="0 0 ([\d.]+) ([\d.]+)"/);
  const inner = svg.slice(svg.indexOf('>', svg.indexOf('<svg')) + 1, svg.lastIndexOf('</svg>'));
  const name = componentName(file);
  entries.push({ name, file, vw: Number(vw), vh: Number(vh) });
  body += `
/** \`logos/svg/${file}\` */
export function ${name}(props: LogoSvgProps) {
  return (
    <LogoSvg viewBoxWidth={${vw}} viewBoxHeight={${vh}} {...props}>
      ${toJsx(inner).split('\n').join('\n      ')}
    </LogoSvg>
  );
}
`;
}

const logos = `${HEADER}import * as React from 'react';
import { LogoSvg } from '../LogoSvg';
import type { LogoSvgProps } from '../LogoSvg';
${body}
/** Every generated logo component, keyed by component name. */
export const logoComponents = {
${entries.map((e) => `  ${e.name},`).join('\n')}
} as const;

export type LogoComponentName = keyof typeof logoComponents;

/** Source file and intrinsic size (viewBox units) for each logo component. */
export const logoMeta: Record<LogoComponentName, { file: string; width: number; height: number }> = {
${entries.map((e) => `  ${e.name}: { file: 'logos/svg/${e.file}', width: ${e.vw}, height: ${e.vh} },`).join('\n')}
};
`;
writeFileSync(join(outDir, 'logos.tsx'), logos);

// ---------------------------------------------------------------- tokens
const palette = JSON.parse(readFileSync(join(root, 'colors', 'palette.json'), 'utf8'));
const camel = (s) => s.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
const tokenList = Object.entries(palette.colors).map(([key, v]) => ({
  key: camel(key),
  cssVar: `--gfi-${key}`,
  hex: v.hex,
  use: v.use,
}));

const tokens = `${HEADER}
/** Brand colors, from \`colors/palette.json\`. */
export const colors = {
${tokenList.map((t) => `  /** ${t.use} */\n  ${t.key}: '${t.hex}',`).join('\n')}
} as const;

export type BrandColor = keyof typeof colors;

/** Colors with their CSS variable name and usage note, in palette order. */
export const colorTokens: ReadonlyArray<{ key: BrandColor; cssVar: string; hex: string; use: string }> = [
${tokenList.map((t) => `  { key: '${t.key}', cssVar: '${t.cssVar}', hex: '${t.hex}', use: ${JSON.stringify(t.use)} },`).join('\n')}
];

/** The same colors as CSS custom properties, e.g. for a \`style\` prop or a \`:root\` rule. */
export const cssVariables: Record<string, string> = {
${tokenList.map((t) => `  '${t.cssVar}': '${t.hex}',`).join('\n')}
};
`;
writeFileSync(join(outDir, 'tokens.ts'), tokens);

console.log(`Generated ${entries.length} logo components and ${tokenList.length} color tokens.`);
